name: Update Text File

on:
  schedule:
    - cron: '8 3 * * *'  # Run daily at 7:08 AM UTC

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add or Modify Text File
        run: |
          echo "This is a simple text file." >> example.txt  # Append instead of overwrite
          # echo "" > example.txt  # Use this line to delete the contents of the text file

      # Optional: Set Git Config
      - name: Set Git Config
        run: |
          git config --global user.email "shoomankhatri@gmail.com"
          git config --global user.name "shoomankhatri" || true  # Handle potential errors (optional)

      - name: Commit and Push
        run: |
          git add example.txt
          git commit -m "Update example.txt"  # Consider more descriptive commit messages
          git push https://github.com/${{ github.repository }} HEAD:${{ github.ref }} || true  # Handle potential errors (optional)
        env:
          GH_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}  # Use your secret name here
